function contactLoad() {
    const contentBody = document.querySelector('.content-body');
    contentBody.textContent = '';
    const contactContent = document.createElement('div');
    contactContent.classList.add('contact-content');
    contentBody.appendChild(contactContent);
    const element1 = document.createElement('div');
    element1.classList.add('elementC');
    contactContent.appendChild(element1);
    const header1 = document.createElement('div');
    header1.classList.add('headerC');
    header1.textContent = "ADDRESS";
    element1.appendChild(header1);
    const text1 = document.createElement('div');
    text1.classList.add('textC');
    element1.appendChild(text1);
    const t1p1 = document.createElement('div');
    t1p1.textContent = "16 Ring Road";
    text1.appendChild(t1p1);
    const t1p2 = document.createElement('div');
    t1p2.textContent = "Delhi-01";
    text1.appendChild(t1p2);
    const element2 = document.createElement('div');
    element2.classList.add('elementC');
    contactContent.appendChild(element2);
    const header2 = document.createElement('div');
    header2.classList.add('headerC');
    header2.textContent = "PHONE";
    element2.appendChild(header2);
    const text2 = document.createElement('div');
    text2.classList.add('textC');
    element2.appendChild(text2);
    const t2p1 = document.createElement('div');
    t2p1.textContent = "+91-0000000000";
    text2.appendChild(t2p1);
    const element3 = document.createElement('div');
    element3.classList.add('elementC');
    contactContent.appendChild(element3);
    const header3 = document.createElement('div');
    header3.classList.add('headerC');
    header3.textContent = "WORKING HOURS";
    element3.appendChild(header3);
    const text3 = document.createElement('div');
    text3.classList.add('textC');
    element3.appendChild(text3);
    text3.textContent = "Everyday from 9 AM to 10 PM";
    const element4 = document.createElement('div');
    element4.classList.add('elementC');
    contactContent.appendChild(element4);
    const header4 = document.createElement('div');
    header4.classList.add('headerC');
    header4.textContent = "EMAIL";
    element4.appendChild(header4);
    const text4 = document.createElement('div');
    text4.classList.add('textC');
    element4.appendChild(text4);
    text4.textContent = "milanocafe@example.com";
}

export {contactLoad};